### ISSUE TITLE
Adicionar .editorconfig

### ISSUE THREAD

**Issue by alisonmonteiro** [theuves/git-cometer#3]
A utilização do [.editorconfig](http://editorconfig.org/) é interessante, pois quem faz um fork do projeto, acaba seguindo os padrões indentação definidos, tamanho de tab ou quantidade de espaços, etc.

Vale a pena dar uma olhada. :+1:

**Comment by theuves** [comment]
Já tinha visto-o em alguns projetos mas nunca tinha usado, gostei bastante. Obrigado pela dica!
